monkeyList = {'darwin','Euler','joule','Xena'};


figure('Renderer', 'painters', 'Position', [100 100 1200 150]);
for monkeyIdx = 1:length(monkeyList)

% High conditions
subplot(1,2*length(monkeyList),(monkeyIdx*2)-1)
donut(...
    [sum(rtcomparison.hiFlag == 1 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx})),...
    sum(rtcomparison.hiFlag == 0 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx}))],...
    {'Non-valid','Valid'},{colors.hi, colors.hi});
legend off
% Low conditions

subplot(1,2*length(monkeyList),monkeyIdx*2)
donut(...
    [sum(rtcomparison.loFlag == 1 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx})),...
    sum(rtcomparison.loFlag == 0 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx}))],...
    {'Non-valid','Valid'},{colors.lo, colors.lo});

legend off

 nSession_RTvio (monkeyIdx,:) = ...
     [sum(rtcomparison.hiFlag == 1 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx})),...
    sum(rtcomparison.hiFlag == 0 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx})),...
    sum(rtcomparison.loFlag == 1 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx})),...
    sum(rtcomparison.loFlag == 0 & strcmp(valuedata_master.monkey,monkeyList{monkeyIdx}))];


end
